version: '3.8'

services:
 web:
  image: 127.0.0.1:5000/seven-task-pis
  build: .
  deploy:
      replicas: 4
  ports:
  - 80:80
  volumes:
  - ./:/app

 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=itmo337980
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: